from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from chef_human.agent.planner import Plan
    from chef_human.agent.parser import ParsedToolCall


class ReActUI(Protocol):
    def on_start(self, task: str) -> None: ...
    def on_planning_start(self) -> None: ...
    def on_plan(self, plan: Plan) -> None: ...
    def on_reasoning_start(self) -> None: ...
    def on_reasoning(self, content: str) -> None: ...
    def on_tool_call(self, tool_call: ParsedToolCall) -> None: ...
    def on_tool_result(self, name: str, result: str) -> None: ...
    def on_replan(self) -> None: ...
    def on_error(self, message: str) -> None: ...

    async def on_approval_request(
        self, tool_call: ParsedToolCall
    ) -> bool | None:
        return None


class NoopUI:
    def on_start(self, task: str) -> None: ...
    def on_planning_start(self) -> None: ...
    def on_plan(self, plan: Plan) -> None: ...
    def on_reasoning_start(self) -> None: ...
    def on_reasoning(self, content: str) -> None: ...
    def on_tool_call(self, tool_call: ParsedToolCall) -> None: ...
    def on_tool_result(self, name: str, result: str) -> None: ...
    def on_replan(self) -> None: ...
    def on_error(self, message: str) -> None: ...

    async def on_approval_request(
        self, tool_call: ParsedToolCall
    ) -> bool | None:
        return None
